common:
  artifact_dir: "mlops_artifacts"
  best_run_dir: "best_run"
  runs_dir: "runs"
  pipeline_steps_dir: "pipeline_steps"
  feature_binning_pkl_path: "feature_binning.pkl"
  standard_scaler_pkl_path: "standard_scaler.pkl"
  feature_selector_pkl_path: "feature_selector.pkl"
  model_pkl_path: "model.pkl"
  estimator_pkl_path: "estimator.pkl"
  run_config_save_path: "run_config.yaml"
  seed: 42

data_ingestion:
  data_ingestion_dir: "data_ingestion"
  data_path: "data/heart.csv"
  raw_data_dir: "raw_data"
  raw_data_path: raw.csv
  ingested_data_dir: "ingested_data"
  train_file_path: train.csv
  test_file_path: test.csv
  train_test_split_ratio: 0.2

data_validation:
  data_validation_dir: "data_validation"
  schema_read_path: "src/mlops/schemas/data_validation_schema.yaml"
  schema_save_path: "data_validation_schema.yaml"
  validation_reports_dir: "validation_reports"
  validation_report_train_path: "validation_report_train.yaml"
  validation_report_test_path: "validation_report_test.yaml"
  validated_data_dir: "validated_data"
  invalidated_data_dir: "invalidated_data"
  valid_train_path: "validated_train.csv"
  valid_test_path: "validated_test.csv"
  invalid_train_path: "invalidated_train.csv"
  invalid_test_path: "invalidated_test.csv"

data_transformation:
  data_transformation_dir: "data_transformation"
  schema_read_path: "src/mlops/schemas/data_transformation_schema.yaml"
  schema_save_path: "data_transformation_schema.yaml"
  preprocessor_objects_dir: "preprocessor_objects"
  standard_scaler_path: "standard_scaler.pkl"
  feature_binning_path: "feature_binning.pkl"
  transformed_data_dir: "transformed_data"
  transformed_train_path: "transformed_train.csv"
  transformed_test_path: "transformed_test.csv"

model_training:
  model_training_dir: "model_training"
  schema_read_path: "src/mlops/schemas/model_training_schema.yaml"
  schema_save_path: "model_training_schema.yaml"
  logistic_regression_dir: "logistic_regression"
  random_forest_dir: "random_forest"
  xgboost_dir: "xgboost"
  catboost_dir: "catboost"
  svc_dir: "svc"
  mlp_dir: "mlp"
  sgd_dir: "sgd"
  tuning_summary_path: "tuning_summary.yaml"
  target_feature: "target"

model_evaluation:
  model_evaluation_dir: "model_evaluation"
  schema_read_path: "src/mlops/schemas/model_evaluation_schema.yaml"
  schema_save_path: "model_evaluation_schema.yaml"
  logistic_regression_dir: "logistic_regression"
  random_forest_dir: "random_forest"
  xgboost_dir: "xgboost"
  catboost_dir: "catboost"
  svc_dir: "svc"
  mlp_dir: "mlp"
  sgd_dir: "sgd"
  evaluation_summary_path: "evaluation_summary.yaml"
  best_model_summary_path: "best_model_summary.yaml"
  target_feature: "target"
