common:
  artifact_dir: "mlops_artifacts"
  seed: 42

data_ingestion:
  data_ingestion_dir: "data_ingestion"
  data_path: "data/heart.csv"
  raw_data_dir: "raw_data"
  raw_data_path: raw.csv
  ingested_data_dir: "ingested_data"
  train_file_path: train.csv
  test_file_path: test.csv
  train_test_split_ratio: 0.2

data_validation:
  data_validation_dir: "data_validation"
  schema_path: "src/mlops/schemas/data_validation_schema.yaml"
  is_validated_train_path: "data_validation_train.yaml"
  is_validated_test_path: "data_validation_test.yaml"
  validated_data_dir: "validated_data"
  invalidated_data_dir: "invalidated_data"
  valid_train_path: "validated_train.csv"
  valid_test_path: "validated_test.csv"
  invalid_train_path: "invalidated_train.csv"
  invalid_test_path: "invalidated_test.csv"

data_transformation:
  data_transformation_dir: "data_transformation"
  schema_path: "src/mlops/schemas/data_transformation_schema.yaml"
  preprocessor_objects_dir: "preprocessor_objects"
  standard_scaler_path: "standard_scaler.pkl"
  transformed_data_dir: "transformed_data"
  transformed_train_path: "transformed_train.csv"
  transformed_test_path: "transformed_test.csv"

model_training:
  model_training_dir: "model_training"
  schema_path: "src/mlops/schemas/model_training_schema.yaml"
  logistic_regression_dir: "logistic_regression"
  random_forest_dir: "random_forest"
  xgboost_dir: "xgboost"
  best_model_path: "best_model.pkl"
  tuning_summary_path: "tuning_summary.yaml"
  feature_selector_path: "feature_selector.pkl"

model_evaluation:
